### ISSUE TITLE
Events like Click not working

### ISSUE THREAD

**Issue by oop106** [rodrigoelp/wpfgesturerecognizer#10]
Maybe I am missing something obvious here, but how can I even let a Button Click event trigger with this package in place?

E.g. if I put the gesturerecognizer triggers on a grid, I still want to be able to click buttons in that grid. It simply doesn't work. I couldn't figure out a workaround with the tap event either.

**Comment by madben2000** [comment]
Any solutions on this?

**Comment by rodrigoelp** [comment]
Hi @oop106,

The way the gesture recognizer was written is a bit greedy as the manipulation API takes over completely and does not allow the routed event to continue down the visual tree.

Could you upload to this issue a sample of what you are trying to achieve?

**Comment by rodrigoelp** [comment]
Hi @oop106,
Are you going to provide a sample that I can take a look?

**Comment by rodrigoelp** [comment]
Hi @oop106 and @madben2000, can you guys provide a sample of what you are trying to achieve?

**Comment by z3phyro** [comment]
Hi... I'm having the same problem.... it more or less goes like this.

I have a grid in which the buttons are placed and when entering this in the header of the grid it intercepts the click gesture I suppose: 

This is my XAML

```
    <Grid HorizontalAlignment="Stretch">
        <i:Interaction.Triggers>
            <recognizer:GestureRecognizer TriggerOnGesture="SwipeLeft">
                <i:InvokeCommandAction Command="{Binding NextArticlesCommand}" />
            </recognizer:GestureRecognizer>
            <recognizer:GestureRecognizer TriggerOnGesture="SwipeRight">
                <i:InvokeCommandAction Command="{Binding PreviousArticlesCommand}" />
            </recognizer:GestureRecognizer>
        </i:Interaction.Triggers>
<Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="Auto" />
        </Grid.ColumnDefinitions>

        <Button Grid.Column="0" Command="{Binding PreviousArticlesCommand}" Style="{StaticResource TouchScreenSwipeButton}">
            <materialDesign:PackIcon Kind="ChevronLeft" Width="25" Height="25"/>
        </Button>

        <Grid Grid.Column="1" VerticalAlignment="Stretch"
                    >
            <Grid.RowDefinitions>
                <RowDefinition Height="35"/>
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>
            <DockPanel Grid.Row="0" Margin="10 0">
                <StackPanel DockPanel.Dock="Left" Orientation="Horizontal">
                    <Button Width="35" Height="35" Style="{StaticResource TopbarToolButtonStyle}" Command="{Binding FilterArticlesCommand}">
                        <materialDesign:PackIcon Width="30" Height="30" Kind="FileFind" />
                    </Button>
                    <TextBox Text="{Binding ArticlesFilterText, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" Width="150"/>
                    <Button Width="35" Height="35" Style="{StaticResource TopbarToolButtonStyle}" Command="{Binding ClearFilterArticlesCommand}">
                        <materialDesign:PackIcon Width="30" Height="30" Kind="Delete" />
                    </Button>
                </StackPanel>
            </DockPanel>

            <TextBlock Grid.Row="1"  Text="{Binding ArticlesNotificationText}" Foreground="{StaticResource MaterialDesignBodyLight}" 
                           FontSize="20" Width="300" TextWrapping="WrapWithOverflow" TextAlignment="Center"  VerticalAlignment="Top" 
                           Margin="0 20 0 0" HorizontalAlignment="Center"/>

            <ItemsControl Grid.Row="1"
                Name="ArticlesWrapPanel1" 
                HorizontalContentAlignment="Stretch"
                HorizontalAlignment="Stretch" 
                VerticalContentAlignment="Stretch"
                VerticalAlignment="Stretch" 
                ItemsSource="{Binding ArticlesFP}" 
                >
                <ItemsControl.ItemsPanel>
                    <ItemsPanelTemplate>
                        <WrapPanel ItemWidth="80" ItemHeight="80" Orientation="Horizontal" HorizontalAlignment="Left" />
                    </ItemsPanelTemplate>
                </ItemsControl.ItemsPanel>
            </ItemsControl>

        </Grid>

        <Button Grid.Column="2" Command="{Binding NextArticlesCommand}" Style="{StaticResource TouchScreenSwipeButton}">
            <materialDesign:PackIcon Kind="ChevronRight" Width="25" Height="25"/>
        </Button>
    </Grid>
```

**Comment by z3phyro** [comment]
Could there be a way to avoid processing the "tap" gesture so the click events actually work?

**Comment by z3phyro** [comment]
Hi...  I tried this

    <i:Interaction.Triggers>
        <r:GestureRecognizer TriggerOnGesture="Tap">
            <ei:CallMethodAction MethodName="Test"  />
        </r:GestureRecognizer>
        <r:GestureRecognizer TriggerOnGesture="SwipeLeft">
            <i:InvokeCommandAction Command="{Binding NextTablesCommand}" />
        </r:GestureRecognizer>
        <r:GestureRecognizer TriggerOnGesture="SwipeRight">
            <i:InvokeCommandAction Command="{Binding PreviousTablesCommand}" />
        </r:GestureRecognizer>
    </i:Interaction.Triggers>

with this in the cs

        [System.Runtime.InteropServices.DllImport("user32.dll")]
        static extern bool SetCursorPos(int x, int y);

        [System.Runtime.InteropServices.DllImport("user32.dll")]
        public static extern void mouse_event(int dwFlags, int dx, int dy, int cButtons, int dwExtraInfo);

        public const int MOUSEEVENTF_LEFTDOWN = 0x02;
        public const int MOUSEEVENTF_LEFTUP = 0x04;

        //This simulates a left mouse click
        public static void LeftMouseClick(int xpos, int ypos)
        {
            SetCursorPos(xpos, ypos);
            mouse_event(MOUSEEVENTF_LEFTDOWN, xpos, ypos, 0, 0);
            mouse_event(MOUSEEVENTF_LEFTUP, xpos, ypos, 0, 0);
        }

        public void Test()
        {
            System.Drawing.Point point = Control.MousePosition;

            LeftMouseClick(point.X, point.Y);
        }

and now it recognizes the click but not the swipe :( 

any help would be great .... thx

**Comment by rodrigoelp** [comment]
Hi @z3phyro, when you intercept the cursor, you are bypassing WPF standard routed events.

I am going to create an example based on your code and check it in the morning. Thanks for the feedback.

**Comment by davidop** [comment]
Hi! How's the example going? I'm having the same issue too

**Comment by rodrigoelp** [comment]
Hi @davidop, haven't had time to inspect these things.

There is another issue that was created, in which they are mentioning that multiple level recognisers are overriding between each other, meaning the event might be captured and handled before any other control gets a chance to raise their own actions. If that is the case, other controls like a button will start responding whilst hosted in a swipeable area.

**Comment by davidop** [comment]
Thanks for the reply, @rodrigoelp. What other issue do you mean?

**Comment by rodrigoelp** [comment]
The issue #14

**Comment by rodrigoelp** [comment]
Hi @davidop, further inspection revealed this issue is not related with #14. The main problem is that I do not get as part of the events any indication there is a button generating the manipulation (ideally the gesture recognizer shouldn't receive any of these events). I will continue looking into this.

**Comment by rodrigoelp** [comment]
Hi guys, looking a bit more into this issue: the manipulation API will capture any event and rerouted internally to the handler without indicating which control is triggering (or at least, I've not found a way to detect the source as a child control of the manipulation device)...

But, there is a way to achieve something similar to what you guys want. Here is my snippet.

```xaml
    <!-- replace the content of a window with the following xaml -->
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition MinHeight="200" />
            <RowDefinition MinHeight="200" />
        </Grid.RowDefinitions>

        <Grid Grid.Row="0">
            <Rectangle x:Name="GestureIndication" Fill="#d3d3d3" Stroke="#939393" Margin="16" StrokeThickness="2" StrokeDashArray="4 2" SnapsToDevicePixels="True" />
            <ListView x:Name="Log" HorizontalAlignment="Right" />
        </Grid>

        <Grid Grid.Row="1" Background="#1fff0000" Margin="16">
            <i:Interaction.Triggers>
                <recognizer:GestureRecognizer TriggerOnGesture="SwipeDown">
                    <ei:ChangePropertyAction TargetName="GestureIndication" PropertyName="Fill" Value="#000066" />
                </recognizer:GestureRecognizer>
                <recognizer:GestureRecognizer TriggerOnGesture="SwipeUp">
                    <ei:ChangePropertyAction TargetName="GestureIndication" PropertyName="Fill" Value="#660066" />
                </recognizer:GestureRecognizer>
            </i:Interaction.Triggers>
        </Grid>
        <Grid Grid.Row="1">
            <Button VerticalAlignment="Center" HorizontalAlignment="Center" Content="Reset color!" Padding="20">
                <i:Interaction.Triggers>
                    <i:EventTrigger EventName="Click">
                        <ei:ChangePropertyAction TargetName="GestureIndication" PropertyName="Fill" Value="Black" />
                    </i:EventTrigger>
                </i:Interaction.Triggers>
            </Button>
        </Grid>
    </Grid>
```

**Notice that**, by moving the 'top layer' controls to a different parent, the manipulation does not detect the gesture as part of itself. This is a workaround to what you guys are trying to achieve.

**Comment by rodrigoelp** [comment]
Closing this issue as there has been no feedback for months.
