### ISSUE TITLE
Prevent Bubbling For Nested Controls

### ISSUE THREAD

**Issue by wm-v-michaels** [rodrigoelp/wpfgesturerecognizer#14]
Hi!  Thanks for creating this.  I have a question/feature request.

First, the use case:  
I have an application that has a swipe left/right which moves between "pages".  This works great using wpfgesturerecognizer.  Inside one of those pages, I have a control that I would like to allow swiping left/right on as well.   When swiping inside that control, I don't want the whole page to get the swipe command.  

I tried using a relay command  and PassEventArgsToCommand="True" to pass the event that way (and use e.handled in the view model), but it looks like wpfgesturerecognizer only passes the Gesture enum.  

It's possible to make it work by setting one or the other to a different number of fingers, but that creates a training issue.

Would it be possible to create a property like "PreventBubble" that stops the event from bubbling up beyond the current control?

Thanks!

**Comment by rodrigoelp** [comment]
Hi @wm-v-michaels, got lost a bit with the explanation.

This is my understanding of your problem:

You got the following code:
```xaml
<Grid x:Name="BottomMostControl" Width="500">
  <i:Interaction.Triggers>
    <r:GestureRecognizer TriggerOnGesture="SwipeLeft">
      <ei:CallMethodAction MethodName="SaySomething" />
    </r:GestureRecognizer>
  </i:Interaction.Triggers>

  <Grid x:Name="TopSwipeControl" Width="200" HorizontalAlignment="Center">
    <i:Interaction.Triggers>
      <r:GestureRecognizer TriggerOnGesture="SwipeLeft">
        <ei:CallMethodAction MethodName="SaySomethingElse" />
      </r:GestureRecognizer>
    </i:Interaction.Triggers>
  </Grid>
</Grid>
```

I think you are using the implementation of mvvm light `RelayCommand`, am I right? I am not sure that I have seen the `PassEventArgsToCommand` in the standard framework so I wouldn't know how to interact with it when calling the `InvokeActions` method of `TriggerBase`.

We do provide the `Gesture` when calling the `InvokeActions`, which might be related to what you described above.

**Comment by wm-v-michaels** [comment]
Yes, that's the perfect example.  I was actually able to achieve what I wanted to achieve by modifying the source and adding 
`e.Handled = true;`
 to the bottom of the HandleManipulationCompleted method.  This basically prevents the event from bubbling up to the higher control and worked like a charm.

I'm going to try and add a dependency property that will let me turn this off and on, but the actual problem is solved by that.  We want that as the default behavior, so really the dependency property is future use :)

**Comment by wm-v-michaels** [comment]
Is that something you'd like added as a pull request?

**Comment by rodrigoelp** [comment]
So, I imagine you are compiling your own version of the library. What I can do is, to take a look at the changes you have made, give it a test and merge it into master. It shouldn't be too much of a problem to republish with this small change.

**Comment by rodrigoelp** [comment]
Hi @wm-v-michaels, I have implemented the fix pretty much as you suggested... will be publishing it soon (I wanted to solve the #10 but realised these are not related)

**Comment by rodrigoelp** [comment]
I have pushed to master in case you want to take a look at the change.
